/*
 * Stella Castura
 * 6/7/2022
 * MapGameGUI.java
 * The map form of my ICS3U summtive
 */

/**
 *
 * @author jumpi
 */
public class MapGUI extends javax.swing.JFrame {

    /**
     * Creates new form MapGUI
     */
    public MapGUI() {
        initComponents();
        //the location string is updated in the main class code so I just get it and spit it out. 
        txtLocation.setText(MainGameGUI.location);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLocation = new javax.swing.JLabel();
        txtLocationTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLocation.setFont(new java.awt.Font("Segoe Print", 0, 12));
        getContentPane().add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 580, 80));

        txtLocationTitle.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        txtLocationTitle.setText("Your Location: ");
        getContentPane().add(txtLocationTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICS3U Summative map.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MapGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtLocation;
    private javax.swing.JLabel txtLocationTitle;
    // End of variables declaration//GEN-END:variables
}
